### ISSUE TITLE
Donot translate not works for hindi and other Indian languages

### ISSUE THREAD

**Issue by Thiru-Malai** [ThioJoe/Auto-Synced-Translated-Dubs#52] opened 2023-02-05 14:51 UTC
Hello, When I put some English text in dont_translate_phrases.txt , it does not get translated to any language. But when I want to translate to Hindi and other Indian languages, it does not skip the translation. I am putting the Hindi text in dont_translate_phrases.txt file.  Is there something you can help with it?

**Comment by avighnac** [comment] 2023-02-08 12:30
If you want to translate English to Hindi, then why would you put the HINDI phrases in the text file instead of the English phrases?

**Comment by ThioJoe** [comment] 2023-02-09 20:35
You actually need to put the text in the original language into the list.

For example, if you are translating from English to Hindi, all the words in the dont_translate file should be in English.

**Comment by Thiru-Malai** [comment] 2023-02-10 09:43
Yeah in my example,  I am using hindi to english translation, and I dont want to translate some words in Hindi. But when I put the Hindi phrases in donot_translate.csv, it gets translated to English. I guess this feature only applies to certain languages. Is it so?

**Comment by avighnac** [comment] 2023-02-11 03:17
Could you provide us with a reproducible example?

**Comment by Thiru-Malai** [comment] 2023-02-11 04:30
Yeah, sure… 
Case – 1: (Working fine as expected) ENG -> Hindi
When I want to translate from English to Hindi , This is My original SRT file:
 
![image](https://user-images.githubusercontent.com/73980589/218239903-b632ba3f-00eb-47b5-9bf1-4f8f4b5237d5.png)

Do_not_translate.csv file:
 
![image](https://user-images.githubusercontent.com/73980589/218239904-63a7ad38-9fb6-4a43-a975-d8908e41c5b1.png)

My translated SRT file(For hindi)(Working Fine)
 
![image](https://user-images.githubusercontent.com/73980589/218239910-c80e6369-1bda-4384-b59e-e9d27216d8b3.png)

Case – 2: (Not working) Hindi -> Eng
Original SRT file:
 
![image](https://user-images.githubusercontent.com/73980589/218239914-948646b0-fc32-44a4-87cd-76e210f20112.png)

Do_not_tranlate.txt file:
 
![image](https://user-images.githubusercontent.com/73980589/218239920-d792ae80-d7bc-45b2-a9ce-cd4c101fd97e.png)

Changed language to be translated to English and also the original language to hindi:
  
![image](https://user-images.githubusercontent.com/73980589/218239925-a5f80d8e-d733-48d5-8159-78b0cbf4d8b9.png)

![image](https://user-images.githubusercontent.com/73980589/218239943-00971c86-e8dc-46ef-9909-2a1266a1d0ff.png)

But the English output somehow gets translated as shown below:
 
![image](https://user-images.githubusercontent.com/73980589/218239946-765b37f6-95d8-4baf-9a09-f015503316f3.png)

**Comment by ThioJoe** [comment] 2023-03-26 04:40
Ok it turns out the regex wasn't working with the Unicode characters. But it should be fixed with the latest release 0.11.2.

**Closed by ThioJoe** 2023-03-26 04:40 UTC
