### ISSUE TITLE
break_until_next'

### ISSUE THREAD

**Issue by TiltedChris** [ThioJoe/Auto-Synced-Translated-Dubs#41] opened 2023-01-11 13:56 UTC
I got following error, how can I fix this, while executing the program
subsDict[str(int(line)-1)]['break_until_next'] = processedTime1 - int(subsDict[str(int(line) - 1)]['end_ms'])
~~~~~~~~^^^^^^^^^^^^^^^^^^^^
KeyError: '1'

**Comment by ilMelle** [comment] 2023-01-11 16:06
Same here

**Comment by ilMelle** [comment] 2023-01-12 09:02
Thanks to a friend of mine, I got it working by changing line 185 of main.py with this:
`if lineNum > 0 and (subsDict.get(str(int(line)-1)) is not None):`

**Comment by ThioJoe** [comment] 2023-01-12 13:59
Can you provide your original srt file?

**Comment by TiltedChris** [comment] 2023-01-12 14:56
Sure. I exported the srt file from adobe premiere

SRT file: https://drive.google.com/file/d/1UKZOA2f-w_oHxy3yfZvWn4ARoVozLB7t/view?usp=share_link

**Comment by ThioJoe** [comment] 2023-01-12 18:31
Hm ok I can reproduce the error, I'll have to see what the issue is

**Comment by ThioJoe** [comment] 2023-01-12 18:40
Ok I think I fixed it. Try using this updated version of main.py: https://github.com/ThioJoe/Auto-Synced-Translated-Dubs/blob/main/main.py

**Comment by TiltedChris** [comment] 2023-01-12 18:55
Thx for your help.
Now i got the next error (HttpError 403) but i have my json file in the folder

**Comment by ThioJoe** [comment] 2023-01-18 00:24
> Now i got the next error (HttpError 403) but i have my json file in the folder
Since that sounds like a different problem, could you open a separate issue with some more details? I'm going to close this one.

**Closed by ThioJoe** 2023-01-18 00:24 UTC
